### ISSUE TITLE
What are the next steps after training

### ISSUE THREAD

**Issue by amiltonwong** [pondruska/DeepTracking#2]
Hi, @pondruska ,

After the training (almost it spent 13 hours in my system), what are the next steps to use the trained model?

Thanks~
Milton

**Comment by pondruska** [comment]
Hi Milton,

That depends, after the model was trained the model weights are saved in the directory _weights_model_ and performance in filtering a sample input stream in _video_model_. It should look something like this:
input:
![input36](https://cloud.githubusercontent.com/assets/9326502/13522873/103b5830-e1ea-11e5-9c1c-63d9c9d49586.png) ![input37](https://cloud.githubusercontent.com/assets/9326502/13522874/103bc3ec-e1ea-11e5-8ac3-5d29ccf699db.png) ![input38](https://cloud.githubusercontent.com/assets/9326502/13522875/103bea66-e1ea-11e5-8a32-879982a06d46.png) ![input39](https://cloud.githubusercontent.com/assets/9326502/13522876/103d41ae-e1ea-11e5-9803-6b94909b1bfc.png)
output:
![output36](https://cloud.githubusercontent.com/assets/9326502/13522842/d6e4f884-e1e9-11e5-936a-91484af84f53.png) ![output37](https://cloud.githubusercontent.com/assets/9326502/13522846/df90fdf2-e1e9-11e5-986e-c041626cd177.png) ![output38](https://cloud.githubusercontent.com/assets/9326502/13522849/e63362b2-e1e9-11e5-8e0a-b7e8d840d72a.png) ![output39](https://cloud.githubusercontent.com/assets/9326502/13522853/f527c4f2-e1e9-11e5-8fd9-e51c2d7fe514.png)
i.e. the network learned to predict even not directly visible objects. Note that the network has never seen those during training and this is purely network's imagination.

Generally, in robotics after the model is trained you would put it on a robot and continuously feed new sensor data through the model using _model:forward(input)_ and use its output further up the robotics stack.

Though there is a lot of room for further research: you can try different network architectures in _model.lua_, try different training procedures or generate your own custom data for training simulating multiple sensors or robot movement. Let us know whether you find something interesting.

best,

Peter
